{{ config(materialized='model_monitor') }}

    MODEL = {{ ref('M1_2_LOCATION_SERVICE_MODEL') }}  
    VERSION = 'LAST'
    FUNCTION = 'PREDICT'
    SOURCE = {{ ref('M1_3_LOCATION_SERVICE_PREDICTION') }}  
    WAREHOUSE = SNOWFLAKE_PS_STANDARD
    REFRESH_INTERVAL = '1 day'
    AGGREGATION_WINDOW = '1 day'
    TIMESTAMP_COLUMN = PREDICTION_TIMESTAMP
    PREDICTION_SCORE_COLUMNS = ('PREDICTED')
    ACTUAL_SCORE_COLUMNS = ('ACTUAL')
