version: 2

models:
- name: M1_LOCATION_SERVICE_TRAINING_S
  docs:
    show: true 
    node_color: "gold" # Use name (such as node_color: purple) or hex code with quotes (such as node_color: "#cd7f32")